---
title: '2021 PSRC HTS: Unweighted Summaries for People with No Reported Trips'
# editor_options:
#   chunk_output_type: console
author: PSRC
date: "Documentation last compiled on `r Sys.Date()`"
output:
  html_document:
    collapsed: yes
    self_contained: yes
    toc: yes
    toc_depth: 4
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '4'
  word_document:
    toc: yes
    toc_depth: '4'
params:
  codebook_path: J:/Projects/Surveys/HHTravel/Survey2021/Data/data_from_rsg_20210803/PSRC_2021_HTS_Combined_Codebook.xlsx
  tab_by: sample_source
  tables: [hts_hh, hts_vehicle, hts_person, hts_day, hts_trip]
  variables_to_exclude: ["hhid", "personid", "tripid", "loc_start_other", "loc_end_other", "arrival_time_hhmm", "depart_time_hhmm", "arrival_time_mam", "depart_time_mam", "final_home_puma10", "survey_year", "hhmember1", "hhmember2", "hhmember3", "hhmember4", "hhmember5", "hhmember6", "hhmember7", "hhmember8", "hhmember9", "hhmember10", "hhmember11", "hhmember12"]
  missing_values: !r c(994, 995, -9998, -9999)
  weight_column: 
  study_name: "PSRC HTS 2021"
---

```{r psrc functions, include = FALSE}
# connecting to Elmer
db.connect <- function() {
  elmer_connection <- dbConnect(odbc(),
                                driver = "SQL Server",
                                server = "AWS-PROD-SQL\\Sockeye",
                                database = "Elmer",
                                trusted_connection = "yes"
  )
}

# a function to read tables and queries from Elmer
read.dt <- function(astring, type =c('table_name', 'sqlquery')) {
  elmer_connection <- db.connect()
  if (type == 'table_name') {
    dtelm <- dbReadTable(elmer_connection, SQL(astring))
  } else {
    dtelm <- dbGetQuery(elmer_connection, SQL(astring))
  }
  dbDisconnect(elmer_connection)
  dtelm
}

two_vars_people_counts_by_sample_source = function(dataset,col_name,var_string){
  
  col_name = enquo(col_name)
  
  
  count_by_var = dataset %>% 
  group_by(sample_source.x,( !!col_name)) %>% 
  summarise (count = n_distinct(personid)) 
  
  ABS_mode = count_by_var %>% 
    filter(sample_source.x == 1) %>% 
    rename (ABS_ppl_count = count) #%>% 
    #mutate(ABS_count_share = round(ABS_ppl_count/sum(ABS_ppl_count)*100,1))
    
    
  panel_mode = count_by_var %>% 
    filter(sample_source.x == 2)%>% 
    rename (panel_ppl_count = count) #%>% 
    #mutate(panel_count_share = round(panel_ppl_count/sum(panel_ppl_count)*100,1))
  
  temp = ABS_mode %>% 
    full_join(panel_mode,  by = var_string) %>% 
    dplyr::select(-c(sample_source.x.x,sample_source.x.y)) %>% 
    rename( "value" := !!col_name)
   # mutate(value = !!col_name)
  
  var_label_table = as.data.frame(value_labels[value_labels$variable %in% c(var_string)] %>% mutate(value = as.double(value))) %>% 
    dplyr::select(value, value_label)
  
  #browser()
  
  temp = temp %>% left_join(var_label_table, by = "value") %>% 
    dplyr::select(-c(value)) %>%
    relocate(value_label) 

  return(temp)
  
}


get_labels = function(dataset,col_name,var_string){
  col_name = enquo(col_name)
  
  var_label_table = as.data.frame(value_labels[value_labels$variable %in% c(var_string)] %>% mutate(value = as.double(value))) %>% 
    dplyr::select(value, value_label)
  
  dataset = dataset %>%
    rename( "value" := !!col_name)
  
  temp = dataset %>% left_join(var_label_table, by = "value") %>% 
    dplyr::select(-c(value)) %>%
    relocate(value_label) 

  return(temp)
  
}
```


```{r setup, include = FALSE, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'}

# Update codebook path above & data input paths below if running outside of RSG!

options(scipen = 99)
options(knitr.kable.NA = '')
library(data.table)
library(knitr)
library(kableExtra)
library(readxl)
library(lubridate)
#library(RPostgres)
library(stringr)
library(ggplot2)
library(odbc)
library(DBI)
library(tidyverse)
source('C:/Users/pbutrina/Documents/GitHub/travel-survey-rsg-psrc-2021/rsg_qaqc/_crosstabs_functions.R')

```


***


```{r get_inputs, include = FALSE, echo = FALSE, cache = FALSE}

# UPDATE folder path if running outside of RSG
# may also need to update file formats/read functions (e.g., read from a database)
elmer_connection <- dbConnect(odbc::odbc(),
                              driver = "SQL Server",
                              server = "AWS-PROD-SQL\\Sockeye",
                              database = "hhts_cleaning",
                              trusted_connection = "yes")
h <- dbGetQuery(elmer_connection,
                "SELECT * FROM dbo.hts_hh")
p <- dbGetQuery(elmer_connection,
                "SELECT * FROM dbo.hts_person")

d <- dbGetQuery(elmer_connection,
                "SELECT * FROM dbo.hts_day")

t <- dbGetQuery(elmer_connection,
                "SELECT * FROM dbo.hts_trip")
```

```{r varvals, cache = TRUE, echo = FALSE, message = FALSE}

variable_labels = 
  read_codebook(
    params$codebook_path,
    varvals = FALSE,
    sheet = 'Variable_List')

setnames(variable_labels, 'label', 'description', skip_absent = TRUE)

value_labels = 
    read_codebook(
    params$codebook_path,
    varvals = TRUE, 
    sheet = 'Value_Labels')

setnames(value_labels, 'label', 'value_label', skip_absent = TRUE)

variable_labels[, common_name := gsub(':.*', '', description)]

value_labels[, value := as.character(value)]

# Change checkbox logic to be the same for each variable

variable_labels[variable %like% 'delivery_', logic := '']
variable_labels[variable %like% 'no_travel_', logic := 'If made no trips on travel day']
variable_labels[variable %like% 'ethnicity_', logic := 'If related adult household member']
variable_labels[variable %like% 'race_', logic := 'If related adult household member']


```
```{r join trips and person, include = FALSE ,message=FALSE,warning=FALSE}
trips_person = left_join(t, p, by = "personid")

trips_person_under17 = trips_person %>% 
                        filter(age < 5)

trips_hh = left_join(t,h, by = "hhid")


```

***
### people with no trips by sample source

```{r,echo=FALSE,message=FALSE,warning=FALSE}

personid_with_trips = t %>% distinct(personid)

ppl_with_no_trips = subset(p, !(personid %in% personid_with_trips$personid))

no_trips_by_ss = ppl_with_no_trips %>% 
                group_by(sample_source) %>% 
                summarise(n_ppl_no_trips=n())

people_with_trips = t %>% 
  group_by(sample_source) %>% 
  summarise (n_ppl_with_trips = n_distinct(personid))

all_people = p %>% 
            group_by(sample_source) %>% 
            summarise (all_ppl = n_distinct(personid))

full_trips = people_with_trips %>% 
              full_join( no_trips_by_ss, by = "sample_source") %>%
              full_join(all_people, by = "sample_source") %>% 
              mutate(share_ppl_no_trips = n_ppl_no_trips*1.0/all_ppl*100)



get_labels(full_trips, sample_source, "sample_source") %>%
  kbl() %>%
  #kable_material(c("striped", "hover"))
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```
***
### no trips by household size by panel vs ABS; 

```{r,echo=FALSE,message=FALSE,warning=FALSE}

ppl_no_trips_hh = ppl_with_no_trips %>% left_join(h, by = "hhid")

hh_size_no_trips = two_vars_people_counts_by_sample_source(ppl_no_trips_hh, hhsize,"hhsize")

hh_size_no_trips %>%
  kbl() %>%
  #kable_material(c("striped", "hover"))
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

```
***
### no trips by household income by panel vs ABS;

```{r,echo=FALSE,message=FALSE,warning=FALSE}
hh_income_no_trips = two_vars_people_counts_by_sample_source(ppl_no_trips_hh, hhincome_detailed,"hhincome_detailed")

hh_income_no_trips %>%
  kbl() %>%
  #kable_material(c("striped", "hover"))
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```
***
### no trips by age by panel vs ABS;
```{r,echo=FALSE,message=FALSE,warning=FALSE}
age_no_trips = two_vars_people_counts_by_sample_source(ppl_no_trips_hh, age,"age")

age_no_trips %>%
  kbl() %>%
  #kable_material(c("striped", "hover"))
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

***
### no trips by worker status by panel vs ABS;
```{r,echo=FALSE,message=FALSE,warning=FALSE}
age_no_trips = two_vars_people_counts_by_sample_source(ppl_no_trips_hh, worker,"worker")

age_no_trips %>%
  kbl() %>%
  #kable_material(c("striped", "hover"))
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

***
### no trips by workplace by panel vs ABS;
```{r,echo=FALSE,message=FALSE,warning=FALSE}
workplace_no_trips = two_vars_people_counts_by_sample_source(ppl_no_trips_hh, workplace,"workplace")

workplace_no_trips %>%
  kbl() %>%
  #kable_material(c("striped", "hover"))
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```
***







