DROP TABLE 
Angela.BUCKLEY17, Angela.CARBONADO17,
ANGELA.DUPONT17, ANGELA.EATONVILLE17,
Angela.EDGEWOOD17, Angela.FIFE17,
ANGELA.FIRCREST17, ANGELA.GIGHARBOR17,
Angela.ORTING17, Angela.PUYALLUP17,
ANGELA.STEILACOOM17, ANGELA.SUMNER17,
Angela.TACOMA17, Angela.UNINCORPORATEDPIERCE17,
ANGELA.UNIVERSITYPLACE17, ANGELA.WILKESON17

GO
